dadosMunicipiosRJ = './RJdata/dadosMunicipiosRJ.xlsx'
limpath = './RJdata/limitrofes.csv'
LatLngPath = './RJdata/LatLng.csv'
xlsDenguePath = './RJdata/Dengue_Brasil_2010-2016_Daniel.xlsx'
mainRJDatapath = './RJdata/mainRJData.csv'